# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94c815938ad5c29401fc436e21eebdb22e4869875f28e029f3bce6d31f0b9dd7e91f90c8263d942a7b3871e7fffc90b64ec00e864cd72ea5e78dff9fbf64ceb5

test:
  secret_key_base: f5365602705f10c99b9647da3d890fdb544694dee8d0e965cf4e49449921d4f15f1f397e119d9e53b5d53d67edd09d89c437195a6edf7c31ee6034d0169000ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
